//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string Course { get; set; }
        public string TeacherName { get; set; }
        public string Email { get; set; }
    }
}
